name: Build and deploy frontend to Azure Web App - vitalpath-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build and export frontend
        working-directory: frontend
        run: |
          npm run build
          zip -r vitalpath-frontend.zip .next static public package.json next.config.js
          mv vitalpath-frontend.zip ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vitalpath-frontend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_088FFAFDF8314C51A103CCEAB6A77838 }}
          package: vitalpath-frontend.zip





